services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
    - .:/srv/blackjack
    ports:
    - 80:80
    - 5173:5173
    extra_hosts:
    - host.docker.internal:host-gateway
    environment:
      APP_ENV: "local"
      LARAVEL_ENV_ENCRYPTION_KEY: "base64:Dt+yA2SxsUkZQaNcwXD4xc2pwhtQ8+03e5cpg/RTF4E="
    command: bash -c "chmod 755 /srv/blackjack/docker/web/start.sh &&
             /srv/blackjack/docker/web/start.sh /srv/blackjack"
    depends_on:
      composer:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  composer:
    build: ./docker/composer
    volumes:
    - .:/srv/blackjack
    command: bash -c "chmod 755 /srv/blackjack/docker/composer/start.sh &&
             /srv/blackjack/docker/composer/start.sh /srv/blackjack"

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10

  valkey:
    build: ./docker/valkey